from flask import Blueprint, request, jsonify, g
from services.cash_payment_service import CashPaymentService
from utils.auth_restrict import require_auth

cash_payment_bp = Blueprint("cash_payment", __name__)

# -----------------------
# STEP 1: CUSTOMER REQUESTS CASH PAYMENT
# -----------------------
@cash_payment_bp.route("/start", methods=["POST"])
@require_auth(roles=("customer",))
def start_cash_payment():
    data = request.get_json()
    cart = data.get("cart", [])

    if not cart:
        return jsonify({"error": "Cart is empty"}), 400

    user_id = g.current_user.id

    try:
        # Only create pending request; code generated by admin
        pending = CashPaymentService.create_pending_payment(
            user_id=user_id,
            cart=cart
        )
        return jsonify({
            "pending_id": pending.id,
            "message": "Cash payment requested, waiting for admin"
        }), 201
    except Exception as e:
        return jsonify({"error": str(e)}), 400

# -----------------------
# STEP 2: TRIGGER CODE GENERATION
# -----------------------
@cash_payment_bp.route("/request-code/<int:pending_id>", methods=["POST"])
@require_auth(roles=("customer",))
def request_cash_code(pending_id):
    try:
        pending = CashPaymentService.generate_code(pending_id)
        return jsonify({
            "code": pending.code,
            "expires_at": pending.expires_at.isoformat()
        }), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 400


# -----------------------
# STEP 3: CUSTOMER CONFIRMS PAYMENT
# -----------------------
@cash_payment_bp.route("/confirm", methods=["POST"])
@require_auth(roles=("customer",))
def confirm_cash():
    code = request.json.get("code")
    if not code:
        return jsonify({"error": "Cash code required"}), 400

    try:
        tx_id = CashPaymentService.confirm_payment(code)
        return jsonify({
            "message": "Payment successful",
            "transaction_id": tx_id,
            "redirect_url": "/success"  # React can use this to redirect
        }), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 400


# -----------------------
# OPTIONAL: UPDATE CART BEFORE PAYMENT CONFIRMATION
# -----------------------
@cash_payment_bp.route("/update-cart", methods=["PUT"])
@require_auth(roles=("customer",))
def update_cart():
    data = request.get_json()
    try:
        CashPaymentService.update_cart(data["code"], data["cart"])
        return jsonify({"message": "Cart updated"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 400


# -----------------------
# OPTIONAL: CANCEL CASH PAYMENT
# -----------------------
@cash_payment_bp.route("/cancel", methods=["POST"])
@require_auth(roles=("customer",))
def cancel_cash():
    code = request.json.get("code")
    if not code:
        return jsonify({"error": "Cash code required"}), 400
    try:
        CashPaymentService.cancel_payment(code)
        return jsonify({"message": "Cash payment cancelled"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 400

